### PR TITLE
Fix/komega 1121 missing active link style in main menu

### PR DESCRIPTION
**Pull request by eTallang**
OMEGA-46

## What is the reason for this change?
Previously, users had difficulties to see where they currently was in the main menu.

### What is the expected result?
With this change, the active main menu button receives an active style.

## How can it be tested and verified?
Check that the implementation complies with the designs in [Figma](https://www.figma.com/file/sJHoScmQRq0hlr6AcHI9WB/Elvia.no?node-id=9732%3A226), and that it complies with the description in the [Jira issue](https://elvia.atlassian.net/browse/OMEGA-46).

### CODE REVIEW

**Comment by OysteinThuen** [comment]
Build #3020 successfully built and deployed.

- Prod: https://5f4e10adfd2dd0dd7823f95a--elvia-prod.netlify.app
- Test: https://5f4e10cc90bc06bc4e6cb2ba--elvia-test.netlify.app

**Comment by OysteinThuen** [comment]
Build #3062 successfully built and deployed.

- Prod: https://5f4e2dd9529e1ace9c84b4c3--elvia-prod.netlify.app
- Test: https://5f4e2dd1ef6c12c892e06133--elvia-test.netlify.app

**Comment by lobunto** [comment]
code, LGTM @eTallang . Just wondering if we also should hide the active state if the search button is clicked.. i may look like the search is in the context of the active tab? Screenshot 2020-09-01 at 13 38 40

**Comment by eTallang** [comment]
> code, LGTM @eTallang . Just wondering if we also should hide the active state if the search button is clicked.. i may look like the search is in the context of the active tab? Screenshot 2020-09-01 at 13 38 40

Malin agreed, so we changed it so that the underline is hidden when the search is active.

**Review by lobunto — APPROVED** [review]
Excellent work! :D

**Pull request merged**
