### PR TITLE
feat(web): add dialog when deleting han phone number

### PR DESCRIPTION
**Pull request by eTallang**
OMEGA-235

## What is the reason for this change?

Previously, there was no confirm-dialog when deleting a phone number on the HAN-port page.

### What is the expected result?

This PR adds a dialog when removing a phone number on the HAN-port page.

### CODE REVIEW

**Comment by eTallang** [comment]
When doing this task, I've used the `Dialog` component without any further modifications, since it provides all the features that I need. However, the UI that is rendered differs from what's designed. I therefore wonder where we should do a change. Is the CSS for the `Dialog` component wrong? Or is it the designs that differ from the specs of the `Dialog` component in the design system?

UI from the design:
image

UI in browser, based on `Dialog` component:
image


The changes are:
* 40px padding top, instead of 32px in designs
* 26px font size on title, instead of 30px in designs
* 40px padding between content and button-row, instead of 32 in designs
* 48px padding bottom, instead of 32px in designs
- 

-

**Comment by lobunto** [comment]
@eTallang is this PR still under design QA?

**Comment by eTallang** [comment]
> @eTallang is this PR still under design QA?

Yes, I'm waiting for a design approval. It's open for code QA though :slightly_smiling_face:

**Review by lobunto — APPROVED** [review]

**Review by steinmy — APPROVED** [review]
Nice and clean fix

**Pull request merged**
